package it.polimi.ingsw.am22.network.common.dto;

import java.io.Serializable;

/**
 * Serializable DTO representing a game card.
 *
 * Data-only, no logic: generated by {@code ModelDtoMapper}
 * from the concrete model classes (characters, buildings, events).
 *
 * @param id          unique card identifier
 * @param category    category (e.g. CHARACTER, BUILDING, EVENT)
 * @param detailType  specific type within the category
 * @param era         era this card belongs to
 * @param minPlayers  minimum number of players for which it is active
 * @param foodCost    food cost ({@code null} if not applicable)
 * @param numStars    stars carried by this card (only Shamans, 0 otherwise)
 */
public record CardDTO(
        String id,
        String category,
        String detailType,
        String era,
        int minPlayers,
        Integer foodCost,
        int numStars
) implements Serializable {
}
